# Generated by Django 6.0.6 on 2026-06-21 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المعيار')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='الوزن النسبي')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='الترتيب')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
            ],
            options={
                'verbose_name': 'معيار تقييم',
                'verbose_name_plural': 'معايير التقييم',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='نص المؤشر')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='evaluations.evaluationdomain', verbose_name='المعيار')),
            ],
            options={
                'verbose_name': 'مؤشر تقييم',
                'verbose_name_plural': 'مؤشرات التقييم',
                'ordering': ['domain__order', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ProgramEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('in_progress', 'قيد التقييم'), ('submitted', 'مرسل للمراجعة'), ('approved', 'معتمد')], default='draft', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='programs.academicyear', verbose_name='العام الأكاديمي')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='programs.program', verbose_name='البرنامج')),
            ],
            options={
                'verbose_name': 'تقييم برنامج',
                'verbose_name_plural': 'تقييمات البرامج',
                'unique_together': {('program', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='IndicatorScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'غير مستوفي'), (2, 'مستوفي جزئيًا'), (3, 'مستوفي'), (4, 'مستوفي بإتقان'), (5, 'مستوفي بتميز')], null=True, verbose_name='درجة التوفر')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='evaluations.evaluationindicator', verbose_name='المؤشر')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='evaluations.programevaluation', verbose_name='التقييم')),
            ],
            options={
                'verbose_name': 'درجة مؤشر',
                'verbose_name_plural': 'درجات المؤشرات',
                'unique_together': {('evaluation', 'indicator')},
            },
        ),
    ]
