# Generated by Django 6.0.6 on 2026-07-10 04:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_activitylog_object_repr'),
        ('evaluations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramEvaluationReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('reviewed', 'معتمد')], default='draft', max_length=20, verbose_name='حالة التقييم العامة')),
                ('overall_auto_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='النسبة الآلية')),
                ('overall_reviewer_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='نسبة المراجع')),
                ('final_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='النسبة النهائية')),
                ('final_status_label', models.CharField(default='غير مستوفي', max_length=100, verbose_name='التقدير النهائي')),
                ('general_notes', models.TextField(blank=True, verbose_name='ملاحظات عامة')),
                ('generated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التوليد / التحديث')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('evaluation_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quality_review', to='dashboard.evaluationfile', verbose_name='ملف بيانات البرنامج')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_program_quality_reviews', to=settings.AUTH_USER_MODEL, verbose_name='تم التوليد بواسطة')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_program_quality_reviews', to=settings.AUTH_USER_MODEL, verbose_name='تم الاعتماد العام بواسطة')),
            ],
            options={
                'verbose_name': 'تقييم جودة البرنامج',
                'verbose_name_plural': 'تقييمات جودة البرامج',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='StandardEvaluationReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_status', models.CharField(choices=[('empty', 'غير محفوظ'), ('draft', 'مسودة'), ('reviewed', 'معتمد')], default='empty', max_length=20, verbose_name='حالة مراجعة المعيار')),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='وزن المعيار')),
                ('auto_score', models.PositiveSmallIntegerField(choices=[(1, 'غير مستوفي'), (2, 'مستوفي جزئيًا'), (3, 'مستوفي'), (4, 'مستوفي بإتقان'), (5, 'مستوفي بتميز')], default=1, verbose_name='درجة النظام')),
                ('reviewer_score', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'غير مستوفي'), (2, 'مستوفي جزئيًا'), (3, 'مستوفي'), (4, 'مستوفي بإتقان'), (5, 'مستوفي بتميز')], null=True, verbose_name='درجة المراجع')),
                ('auto_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة النظام')),
                ('reviewer_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='نسبة المراجع')),
                ('auto_weighted_score', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='الدرجة الوزنية الآلية')),
                ('reviewer_weighted_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='الدرجة الوزنية للمراجع')),
                ('auto_notes', models.TextField(blank=True, verbose_name='ملاحظات النظام')),
                ('reviewer_notes', models.TextField(blank=True, verbose_name='ملاحظات المراجع')),
                ('strengths', models.TextField(blank=True, verbose_name='نقاط القوة')),
                ('weaknesses', models.TextField(blank=True, verbose_name='نقاط الضعف')),
                ('improvement_plan', models.TextField(blank=True, verbose_name='خطة التحسين')),
                ('execution_time', models.CharField(blank=True, max_length=255, verbose_name='زمن التنفيذ')),
                ('modified_by_reviewer', models.BooleanField(default=False, verbose_name='تم تعديل تقييم النظام')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ اعتماد المعيار')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standard_reviews', to='evaluations.programevaluationreview', verbose_name='تقييم البرنامج')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_quality_standards', to=settings.AUTH_USER_MODEL, verbose_name='تم اعتماد المعيار بواسطة')),
                ('saved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_quality_standard_drafts', to=settings.AUTH_USER_MODEL, verbose_name='تم الحفظ بواسطة')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_standard_reviews', to='dashboard.qualitystandard', verbose_name='المعيار')),
            ],
            options={
                'verbose_name': 'تقييم معيار',
                'verbose_name_plural': 'تقييم المعايير',
                'ordering': ['standard__number'],
                'unique_together': {('review', 'standard')},
            },
        ),
        migrations.CreateModel(
            name='IndicatorEvaluationReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_key', models.CharField(max_length=120, verbose_name='مفتاح المؤشر')),
                ('indicator_text', models.TextField(verbose_name='نص المؤشر')),
                ('auto_score', models.PositiveSmallIntegerField(choices=[(1, 'غير مستوفي'), (2, 'مستوفي جزئيًا'), (3, 'مستوفي'), (4, 'مستوفي بإتقان'), (5, 'مستوفي بتميز')], default=1, verbose_name='درجة النظام')),
                ('reviewer_score', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'غير مستوفي'), (2, 'مستوفي جزئيًا'), (3, 'مستوفي'), (4, 'مستوفي بإتقان'), (5, 'مستوفي بتميز')], null=True, verbose_name='درجة المراجع')),
                ('auto_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة تحقق المؤشر')),
                ('auto_notes', models.TextField(blank=True, verbose_name='ملاحظة النظام')),
                ('reviewer_notes', models.TextField(blank=True, verbose_name='ملاحظة المراجع')),
                ('data_snapshot', models.JSONField(blank=True, default=dict, verbose_name='تفاصيل الفحص الآلي')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('standard_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_reviews', to='evaluations.standardevaluationreview', verbose_name='تقييم المعيار')),
            ],
            options={
                'verbose_name': 'تقييم مؤشر',
                'verbose_name_plural': 'تقييم المؤشرات',
                'ordering': ['id'],
                'unique_together': {('standard_review', 'indicator_key')},
            },
        ),
    ]
