# Generated by Django 6.0.6 on 2026-07-02 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'evaluations',
            '0002_programevaluationreview_standardevaluationreview_and_more',
        ),
        migrations.swappable_dependency(
            settings.AUTH_USER_MODEL
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name='programevaluationreview',
            name='reviewed_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='reviewed_program_quality_reviews',
                to=settings.AUTH_USER_MODEL,
                verbose_name='تم الاعتماد العام بواسطة',
            ),
        ),

        migrations.AlterField(
            model_name='programevaluationreview',
            name='status',
            field=models.CharField(
                choices=[
                    ('draft', 'مسودة'),
                    ('reviewed', 'معتمد'),
                ],
                default='draft',
                max_length=20,
                verbose_name='حالة التقييم العامة',
            ),
        ),
    ]