# Generated by Django 6.0.6 on 2026-06-23 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم البرنامج')),
                ('specialization', models.CharField(blank=True, max_length=200, null=True, verbose_name='التخصص / المسار')),
                ('start_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='سنة بداية البرنامج')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'برنامج أكاديمي',
                'verbose_name_plural': 'البرامج الأكاديمية',
                'ordering': ['name', 'specialization'],
            },
        ),
        migrations.CreateModel(
            name='QualityStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='رقم المعيار')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان المعيار')),
                ('weight', models.PositiveIntegerField(default=0, verbose_name='الوزن النسبي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'معيار جودة',
                'verbose_name_plural': 'معايير الجودة',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20, verbose_name='سنة التقييم')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('in_progress', 'قيد الإدخال'), ('completed', 'مكتمل')], default='draft', max_length=30, verbose_name='حالة الملف')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_files', to='dashboard.academicprogram', verbose_name='البرنامج')),
            ],
            options={
                'verbose_name': 'ملف تقييم',
                'verbose_name_plural': 'ملفات التقييم',
                'ordering': ['-academic_year', 'program'],
                'unique_together': {('program', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='EducationProcessRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=250, verbose_name='البند')),
                ('status', models.CharField(blank=True, max_length=150, null=True, verbose_name='الحالة')),
                ('value', models.CharField(blank=True, max_length=100, null=True, verbose_name='النسبة / العدد')),
                ('evidence', models.CharField(blank=True, max_length=250, null=True, verbose_name='المرفق / الشاهد')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('evaluation_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_process_records', to='dashboard.evaluationfile', verbose_name='ملف التقييم')),
            ],
            options={
                'verbose_name': 'مؤشر عملية تعليمية',
                'verbose_name_plural': 'مؤشرات العملية التعليمية',
            },
        ),
        migrations.CreateModel(
            name='CourseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=250, verbose_name='اسم المقرر')),
                ('course_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='رمز المقرر')),
                ('credit_hours', models.PositiveIntegerField(default=0, verbose_name='الساعات')),
                ('level', models.CharField(blank=True, max_length=100, null=True, verbose_name='المستوى')),
                ('requirement_type', models.CharField(blank=True, max_length=150, null=True, verbose_name='نوع المتطلب')),
                ('has_specification', models.BooleanField(default=False, verbose_name='له توصيف')),
                ('evaluation_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_records', to='dashboard.evaluationfile', verbose_name='ملف التقييم')),
            ],
            options={
                'verbose_name': 'مقرر دراسي',
                'verbose_name_plural': 'المقررات الدراسية',
            },
        ),
        migrations.CreateModel(
            name='FacultyMemberRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='الاسم')),
                ('qualification', models.CharField(blank=True, max_length=200, null=True, verbose_name='المؤهل')),
                ('qualification_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='سنة الحصول عليه')),
                ('academic_rank', models.CharField(blank=True, max_length=200, null=True, verbose_name='المرتبة الأكاديمية')),
                ('rank_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الحصول عليها')),
                ('employment_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='متفرغ / غير متفرغ')),
                ('teaching_load', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='النصاب التدريسي')),
                ('evaluation_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_members', to='dashboard.evaluationfile', verbose_name='ملف التقييم')),
            ],
            options={
                'verbose_name': 'عضو هيئة تدريس',
                'verbose_name_plural': 'أعضاء هيئة التدريس',
            },
        ),
        migrations.CreateModel(
            name='GraduateRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20, verbose_name='العام الجامعي')),
                ('graduates_count', models.PositiveIntegerField(default=0, verbose_name='عدد الخريجين')),
                ('cumulative_gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='المعدل التراكمي')),
                ('evaluation_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graduate_records', to='dashboard.evaluationfile', verbose_name='ملف التقييم')),
            ],
            options={
                'verbose_name': 'سجل خريجين',
                'verbose_name_plural': 'أعداد الخريجين',
            },
        ),
        migrations.CreateModel(
            name='InfrastructureRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_type', models.CharField(max_length=200, verbose_name='نوع المرفق')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='العدد')),
                ('area', models.CharField(blank=True, max_length=100, null=True, verbose_name='المساحة')),
                ('equipment', models.TextField(blank=True, null=True, verbose_name='التجهيزات')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('evaluation_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infrastructure_records', to='dashboard.evaluationfile', verbose_name='ملف التقييم')),
            ],
            options={
                'verbose_name': 'بنية مادية',
                'verbose_name_plural': 'البنية المادية',
            },
        ),
        migrations.CreateModel(
            name='LibrarySourceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(max_length=150, verbose_name='نوع المصدر')),
                ('title', models.CharField(max_length=250, verbose_name='العنوان / الوصف')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='العدد')),
                ('release_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='سنة الإصدار')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('evaluation_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_sources', to='dashboard.evaluationfile', verbose_name='ملف التقييم')),
            ],
            options={
                'verbose_name': 'مصدر مكتبي',
                'verbose_name_plural': 'مصادر المكتبة',
            },
        ),
        migrations.CreateModel(
            name='StandardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_data', models.JSONField(blank=True, default=dict, verbose_name='بيانات الحقول العامة')),
                ('completion_status', models.CharField(choices=[('empty', 'فارغ'), ('partial', 'مكتمل جزئيًا'), ('complete', 'مكتمل')], default='empty', max_length=30, verbose_name='حالة الاكتمال')),
                ('completion_percentage', models.PositiveIntegerField(default=0, verbose_name='نسبة الاكتمال')),
                ('saved_as_draft', models.BooleanField(default=True, verbose_name='محفوظ كمسودة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('evaluation_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standard_entries', to='dashboard.evaluationfile', verbose_name='ملف التقييم')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='dashboard.qualitystandard', verbose_name='المعيار')),
            ],
            options={
                'verbose_name': 'بيانات معيار',
                'verbose_name_plural': 'بيانات المعايير',
                'ordering': ['standard__number'],
                'unique_together': {('evaluation_file', 'standard')},
            },
        ),
        migrations.CreateModel(
            name='EvidenceAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='اسم المرفق')),
                ('file', models.FileField(upload_to='evidence_attachments/', verbose_name='الملف')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('standard_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='dashboard.standardentry', verbose_name='بيانات المعيار')),
            ],
            options={
                'verbose_name': 'مرفق شاهد',
                'verbose_name_plural': 'مرفقات الشواهد',
            },
        ),
        migrations.CreateModel(
            name='StudentLevelCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(max_length=100, verbose_name='المستوى')),
                ('male_count', models.PositiveIntegerField(default=0, verbose_name='عدد الطلاب')),
                ('female_count', models.PositiveIntegerField(default=0, verbose_name='عدد الطالبات')),
                ('evaluation_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_level_counts', to='dashboard.evaluationfile', verbose_name='ملف التقييم')),
            ],
            options={
                'verbose_name': 'عدد الطلبة حسب المستوى',
                'verbose_name_plural': 'أعداد الطلبة حسب المستويات',
            },
        ),
    ]
