# Generated by Django 6.0.6 on 2026-06-25 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduaterecord',
            name='female_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='graduaterecord',
            name='male_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
