# Generated by Django 6.0.6 on 2026-06-27 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_graduaterecord_female_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataEntryTableRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_key', models.CharField(blank=True, default='', max_length=80, verbose_name='مفتاح المعيار')),
                ('table_key', models.CharField(max_length=120, verbose_name='معرف الجدول')),
                ('table_title', models.CharField(blank=True, default='', max_length=255, verbose_name='عنوان الجدول')),
                ('rows', models.JSONField(blank=True, default=list, verbose_name='صفوف الجدول')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('evaluation_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_table_records', to='dashboard.evaluationfile', verbose_name='ملف التقييم')),
            ],
            options={
                'verbose_name': 'سجل جدول إدخال بيانات',
                'verbose_name_plural': 'سجلات جداول إدخال البيانات',
                'ordering': ['standard_key', 'table_key'],
                'indexes': [models.Index(fields=['evaluation_file', 'table_key'], name='dashboard_d_evaluat_354275_idx'), models.Index(fields=['standard_key'], name='dashboard_d_standar_324c1e_idx')],
                'unique_together': {('evaluation_file', 'table_key')},
            },
        ),
    ]
