# Generated by Django 6.0.6 on 2026-07-07 14:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_dataentrytablerecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'دخول للنظام'), ('logout', 'خروج من النظام'), ('create', 'إضافة'), ('update', 'تعديل'), ('delete', 'حذف')], max_length=20, verbose_name='نوع العملية')),
                ('model_name', models.CharField(blank=True, default='', max_length=150, verbose_name='القسم')),
                ('object_repr', models.CharField(blank=True, default='', max_length=255, verbose_name='السجل')),
                ('message', models.TextField(blank=True, default='', verbose_name='وصف العملية')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='وقت العملية')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboard_activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل نشاط',
                'verbose_name_plural': 'سجل نشاط المستخدمين',
                'ordering': ['-created_at'],
            },
        ),
    ]
