# Generated by Django 6.0.6 on 2026-07-08 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_activitylog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-created_at'], 'verbose_name': 'سجل نشاط', 'verbose_name_plural': 'سجل نشاط النظام'},
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='message',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='changes',
            field=models.TextField(blank=True, verbose_name='تفاصيل التغيير'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='object_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='رقم السجل'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='section',
            field=models.CharField(blank=True, max_length=150, verbose_name='القسم'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='url',
            field=models.TextField(blank=True, verbose_name='الرابط'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='user_agent',
            field=models.TextField(blank=True, verbose_name='الجهاز / المتصفح'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('login', 'تسجيل دخول'), ('create', 'إضافة'), ('update', 'تعديل'), ('delete', 'حذف')], max_length=20, verbose_name='نوع العملية'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='model_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='نوع البيانات'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='object_repr',
            field=models.CharField(blank=True, max_length=255, verbose_name='العنصر'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
    ]
