# Generated by Django 6.0.6 on 2026-07-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_activitylog_options_remove_activitylog_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='standard_label',
            field=models.CharField(blank=True, max_length=150, verbose_name='المعيار'),
        ),
    ]
