# Generated by Django 6.0.6 on 2026-07-10 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_activitylog_standard_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='object_repr',
            field=models.CharField(blank=True, max_length=255, verbose_name='البرنامج'),
        ),
    ]
