# Generated by Django 6.0.6 on 2026-07-10 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_activitylog_object_repr'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportExportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(blank=True, default='all', max_length=80, verbose_name='معرف نوع التقرير')),
                ('report_title', models.CharField(max_length=255, verbose_name='نوع التقرير')),
                ('program_name', models.CharField(blank=True, default='اختار البرنامج', max_length=255, verbose_name='البرنامج')),
                ('college_name', models.CharField(blank=True, default='جميع الكليات', max_length=255, verbose_name='الكلية')),
                ('academic_year', models.CharField(blank=True, default='جميع السنوات', max_length=30, verbose_name='السنة الأكاديمية')),
                ('export_format', models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'Excel')], max_length=20, verbose_name='صيغة التصدير')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التصدير')),
                ('exported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboard_report_exports', to=settings.AUTH_USER_MODEL, verbose_name='تم التصدير بواسطة')),
            ],
            options={
                'verbose_name': 'سجل تصدير تقرير',
                'verbose_name_plural': 'سجل تصدير التقارير',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='dashboard_r_created_76941c_idx'), models.Index(fields=['report_type', 'export_format'], name='dashboard_r_report__e29395_idx'), models.Index(fields=['program_name', 'academic_year'], name='dashboard_r_program_3508c0_idx')],
            },
        ),
    ]
