# Generated by Django 6.0.6 on 2026-07-16 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_reportexportlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evaluationfile',
            options={'default_permissions': ('view',), 'ordering': ['-academic_year', 'program'], 'verbose_name': 'ملف تقييم', 'verbose_name_plural': 'ملفات التقييم'},
        ),
        migrations.AlterModelOptions(
            name='standardentry',
            options={'default_permissions': ('view',), 'ordering': ['standard__number'], 'verbose_name': 'بيانات معيار', 'verbose_name_plural': 'بيانات المعايير'},
        ),
    ]
