# Generated by Django 6.0.6 on 2026-07-16 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_evaluationfile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'default_permissions': ('view',), 'ordering': ['-created_at'], 'verbose_name': 'سجل نشاط', 'verbose_name_plural': 'سجل نشاط النظام'},
        ),
    ]
