# Generated by Django 6.0.6 on 2026-07-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_activitylog_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evaluationfile',
            options={'default_permissions': ('view',), 'ordering': ['-academic_year', 'program'], 'verbose_name': 'ملف برنامج أكاديمي', 'verbose_name_plural': 'ملفات البرامج الأكاديمية'},
        ),
        migrations.AlterField(
            model_name='evaluationfile',
            name='academic_year',
            field=models.CharField(max_length=20, verbose_name='السنة الأكاديمية'),
        ),
    ]
