# Generated by Django 6.0.6 on 2026-06-21 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='العام الأكاديمي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'عام أكاديمي',
                'verbose_name_plural': 'الأعوام الأكاديمية',
            },
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الكلية')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
            ],
            options={
                'verbose_name': 'كلية',
                'verbose_name_plural': 'الكليات',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم القسم')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='programs.college', verbose_name='الكلية')),
            ],
            options={
                'verbose_name': 'قسم',
                'verbose_name_plural': 'الأقسام',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم البرنامج')),
                ('qualification_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع المؤهل')),
                ('program_type', models.CharField(choices=[('independent', 'مستقل'), ('joint', 'مشترك'), ('multiple', 'متعدد')], default='independent', max_length=20, verbose_name='نوع البرنامج')),
                ('study_system', models.CharField(blank=True, max_length=100, null=True, verbose_name='نظام الدراسة')),
                ('duration', models.CharField(blank=True, max_length=100, null=True, verbose_name='مدة البرنامج')),
                ('program_manager', models.CharField(blank=True, max_length=200, null=True, verbose_name='مسؤول البرنامج')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='الهاتف')),
                ('website', models.URLField(blank=True, null=True, verbose_name='الموقع الإلكتروني')),
                ('address', models.TextField(blank=True, null=True, verbose_name='العنوان')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='programs.department', verbose_name='القسم')),
            ],
            options={
                'verbose_name': 'برنامج أكاديمي',
                'verbose_name_plural': 'البرامج الأكاديمية',
            },
        ),
    ]
