# Generated by Django 6.0.6 on 2026-06-30 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='start_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='سنة بداية البرنامج'),
        ),
    ]
