# Generated by Django 6.0.6 on 2026-06-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_alter_program_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='college',
        ),
        migrations.RemoveField(
            model_name='program',
            name='department',
        ),
        migrations.AlterModelOptions(
            name='academicyear',
            options={'ordering': ['-name'], 'verbose_name': 'عام أكاديمي', 'verbose_name_plural': 'الأعوام الأكاديمية'},
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['name', 'specialization', 'start_year'], 'verbose_name': 'برنامج أكاديمي', 'verbose_name_plural': 'البرامج الأكاديمية'},
        ),
        migrations.RemoveField(
            model_name='program',
            name='address',
        ),
        migrations.RemoveField(
            model_name='program',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='program',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='program',
            name='email',
        ),
        migrations.RemoveField(
            model_name='program',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='program',
            name='program_manager',
        ),
        migrations.RemoveField(
            model_name='program',
            name='program_type',
        ),
        migrations.RemoveField(
            model_name='program',
            name='qualification_type',
        ),
        migrations.RemoveField(
            model_name='program',
            name='study_system',
        ),
        migrations.RemoveField(
            model_name='program',
            name='website',
        ),
        migrations.AddField(
            model_name='program',
            name='specialization',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='التخصص'),
        ),
        migrations.AlterField(
            model_name='program',
            name='start_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='سنة الإنشاء'),
        ),
        migrations.DeleteModel(
            name='College',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
