# Generated by Django 6.0.6 on 2026-07-10 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0008_program_created_at_program_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='program',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='program',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='program',
            name='updated_by',
        ),
    ]
