# Generated by Django 6.0.6 on 2026-07-10 04:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0009_remove_program_created_at_remove_program_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الكلية')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
            ],
            options={
                'verbose_name': 'كلية',
                'verbose_name_plural': 'الكليات',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='program',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='العنوان'),
        ),
        migrations.AddField(
            model_name='program',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AddField(
            model_name='program',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='مدة البرنامج'),
        ),
        migrations.AddField(
            model_name='program',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AddField(
            model_name='program',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='الهاتف'),
        ),
        migrations.AddField(
            model_name='program',
            name='program_manager',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='مسؤول البرنامج'),
        ),
        migrations.AddField(
            model_name='program',
            name='program_type',
            field=models.CharField(choices=[('independent', 'مستقل'), ('joint', 'مشترك'), ('multiple', 'متعدد')], default='independent', max_length=20, verbose_name='نوع البرنامج'),
        ),
        migrations.AddField(
            model_name='program',
            name='qualification_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع المؤهل'),
        ),
        migrations.AddField(
            model_name='program',
            name='study_system',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نظام الدراسة'),
        ),
        migrations.AddField(
            model_name='program',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='الموقع الإلكتروني'),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم القسم')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='programs.college', verbose_name='الكلية')),
            ],
            options={
                'verbose_name': 'قسم',
                'verbose_name_plural': 'الأقسام',
                'ordering': ['college__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='program',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs', to='programs.department', verbose_name='القسم'),
        ),
    ]
