# Generated by Django 6.0.6 on 2026-07-02 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0003_dataentrytablerecord'),
        ('evaluations', '0003_standardevaluationreview_review_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImprovementPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='رقم المعيار')),
                ('standard_title', models.CharField(blank=True, max_length=255, verbose_name='عنوان المعيار')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان خطة التحسين')),
                ('gap_description', models.TextField(blank=True, verbose_name='وصف الفجوة')),
                ('improvement_action', models.TextField(verbose_name='الإجراء التحسيني')),
                ('responsible_party', models.CharField(blank=True, max_length=255, verbose_name='الجهة المسؤولة')),
                ('priority', models.CharField(choices=[('high', 'عالية'), ('medium', 'متوسطة'), ('low', 'منخفضة')], default='medium', max_length=20, verbose_name='الأولوية')),
                ('status', models.CharField(choices=[('proposed', 'مقترحة'), ('in_progress', 'قيد التنفيذ'), ('completed', 'مكتملة'), ('closed', 'مغلقة')], default='proposed', max_length=20, verbose_name='حالة الخطة')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاريخ البداية')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء المتوقع')),
                ('success_indicator', models.TextField(blank=True, verbose_name='مؤشر الإنجاز')),
                ('required_evidence', models.TextField(blank=True, verbose_name='الدليل المطلوب')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('evaluation_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='improvement_plans', to='dashboard.evaluationfile', verbose_name='ملف التقييم')),
                ('standard_review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='improvement_plans', to='evaluations.standardevaluationreview', verbose_name='المعيار المرتبط')),
            ],
            options={
                'verbose_name': 'خطة تحسين',
                'verbose_name_plural': 'خطط التحسين',
                'ordering': ['-updated_at'],
            },
        ),
    ]
