"""
Django settings for quality_system project.

Generated by 'django-admin startproject' using Django 6.0.6.
"""

import os

from pathlib import Path

import dj_database_url

# ============================================================
# المسارات الأساسية
# ============================================================

BASE_DIR = Path(__file__).resolve().parent.parent


# ============================================================
# إعدادات الأمان والتطوير
# ============================================================

# ============================================================
# إعدادات الأمان والتطوير
# ============================================================

SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-local-development-only-change-before-deploy",
)

# محليًا يكون True، وعلى Render يصبح False تلقائيًا.
DEBUG = "RENDER" not in os.environ


ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
]


# Render يضيف اسم نطاق الخدمة تلقائيًا في هذا المتغير.
RENDER_EXTERNAL_HOSTNAME = os.environ.get(
    "RENDER_EXTERNAL_HOSTNAME"
)

if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(
        RENDER_EXTERNAL_HOSTNAME
    )


CSRF_TRUSTED_ORIGINS = []

if RENDER_EXTERNAL_HOSTNAME:
    CSRF_TRUSTED_ORIGINS.append(
        f"https://{RENDER_EXTERNAL_HOSTNAME}"
    )


# ============================================================
# التطبيقات
# ============================================================

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "programs.apps.ProgramsConfig",
    "evaluations",
    "dashboard.apps.DashboardConfig",
    "reports",
    "improvements.apps.ImprovementsConfig",
]


# ============================================================
# Middleware
# ============================================================

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",

    # حفظ المستخدم الحالي لتسجيل النشاط
    "dashboard.middleware.CurrentUserMiddleware",

    # حماية صفحات النظام وإجبار المستخدم على تسجيل الدخول
    "dashboard.middleware.MainSystemLoginRequiredMiddleware",

    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# ============================================================
# الروابط والقوالب
# ============================================================

ROOT_URLCONF = "quality_system.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "quality_system.wsgi.application"


# ============================================================
# قاعدة البيانات
# ============================================================

# ============================================================
# قاعدة البيانات
# ============================================================

DATABASE_URL = os.environ.get(
    "DATABASE_URL"
)


if DATABASE_URL:
    # قاعدة PostgreSQL المستضافة على Render
    DATABASES = {
        "default": dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,
        )
    }

else:
    # قاعدة PostgreSQL المحلية على جهازك
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",

            "NAME": os.environ.get(
                "LOCAL_DB_NAME",
                "academic_quality_db",
            ),

            "USER": os.environ.get(
                "LOCAL_DB_USER",
                "academic_user",
            ),

            "PASSWORD": os.environ.get(
                "LOCAL_DB_PASSWORD",
                "",
            ),

            "HOST": os.environ.get(
                "LOCAL_DB_HOST",
                "localhost",
            ),

            "PORT": os.environ.get(
                "LOCAL_DB_PORT",
                "5432",
            ),
        }
    }


# ============================================================
# التحقق من كلمات المرور
# ============================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "MinimumLengthValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "CommonPasswordValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "NumericPasswordValidator"
        ),
    },
]


# ============================================================
# اللغة والتوقيت
# ============================================================

LANGUAGE_CODE = "ar"

TIME_ZONE = "Asia/Aden"

USE_I18N = True

USE_TZ = True


# ============================================================
# تسجيل الدخول والخروج
# ============================================================

LOGIN_URL = "/login/"
LOGIN_REDIRECT_URL = "/home/"
LOGOUT_REDIRECT_URL = "/"


# ============================================================
# الملفات الثابتة والمرفوعة
# ============================================================

# ============================================================
# الملفات الثابتة والمرفوعة
# ============================================================

STATIC_URL = "/static/"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATIC_ROOT = BASE_DIR / "staticfiles"


STORAGES = {
    # مؤقتًا تبقى المرفقات محلية.
    # سنغير هذا الجزء إلى Cloudflare R2 لاحقًا.
    "default": {
        "BACKEND": (
            "django.core.files.storage."
            "FileSystemStorage"
        ),
    },

    # ملفات CSS وJavaScript والصور الثابتة
    "staticfiles": {
        "BACKEND": (
            "whitenoise.storage."
            "CompressedManifestStaticFilesStorage"
        ),
    },
}


MEDIA_URL = "/media/"

MEDIA_ROOT = BASE_DIR / "media"

# ============================================================
# المفتاح الأساسي الافتراضي
# ============================================================

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
